import type { Metadata } from "next"
import { Check, Code2, FileText, Github, Globe2, Linkedin, MapPin, MoveRight, Twitter } from "lucide-react"
import { portfolio } from "@/data/portfolio"
import { ThemeToggle } from "./theme-toggle"

export const metadata: Metadata = { title: `${portfolio.profile.name} - Portfolio`, description: portfolio.profile.tagline }

function Divider() { return <div className="stripes h-8 border-y border-line" aria-hidden="true" /> }
function Section({ id, title, count, children }: { id: string; title: string; count?: number; children: React.ReactNode }) { return <section id={id} className="border-x border-line scroll-mt-16"><div className="flex items-center justify-between border-b border-line px-4 py-3"><h2 className="font-mono text-xs uppercase tracking-[.18em] text-muted"><a href={`#${id}`} className="hover:text-foreground">{title}</a>{count ? <span className="ml-2 text-foreground/40">({count})</span> : null}</h2><span className="font-mono text-xs text-muted/60">+</span></div>{children}</section> }
function SocialIcon({ label }: { label: string }) { if (label === "X") return <Twitter className="size-4" />; if (label === "LinkedIn") return <Linkedin className="size-4" />; if (label === "GitHub") return <Github className="size-4" />; if (label === "LeetCode") return <Code2 className="size-4" />; return <FileText className="size-4" /> }

export default function Home() {
 return <main className="mx-auto max-w-3xl px-2 py-2 sm:py-8">
    <nav className="sticky top-2 z-10 mb-2 flex items-center justify-between border border-line bg-background/90 px-3 py-2 backdrop-blur sm:top-4"><a href="#top" className="font-mono text-xs font-semibold tracking-wider">PORTFOLIO<span className="text-accent">.</span></a><div className="flex items-center gap-4"><div className="hidden gap-4 font-mono text-xs text-muted sm:flex"><a href="#experience" className="hover:text-foreground">Experience</a><a href="#projects" className="hover:text-foreground">Projects</a><a href="#contact" className="hover:text-foreground">Contact</a></div><ThemeToggle /></div></nav>
  <div id="top" className="border border-line bg-card"><header className="grid gap-8 border-b border-line p-5 sm:grid-cols-[1fr_180px] sm:p-8"><div className="flex flex-col justify-end"><p className="mb-10 font-mono text-xs uppercase tracking-[.18em] text-muted">Hello, I&apos;m</p><h1 className="text-4xl font-medium tracking-tight sm:text-6xl">{portfolio.profile.name}</h1><p className="mt-4 max-w-md text-lg leading-relaxed text-muted">{portfolio.profile.tagline}</p></div><div className="stripes flex aspect-square items-center justify-center border border-line sm:aspect-auto"><div className="flex size-28 items-center justify-center rounded-full bg-foreground text-5xl text-background">?</div></div></header><div className="grid divide-y divide-line sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="flex items-center gap-2 px-5 py-4 text-sm"><MapPin className="size-4 text-accent" />{portfolio.profile.location}</div><div className="px-5 py-4 text-sm text-muted">{portfolio.profile.pronouns}</div><div className="flex items-center gap-2 px-5 py-4 text-sm"><span className="size-2 rounded-full bg-emerald-500" />{portfolio.profile.availability}</div></div></div>
  <Divider />
  <Section id="about" title="About"><div className="grid gap-6 p-5 sm:grid-cols-[1fr_1.4fr] sm:p-8"><p className="font-mono text-xs uppercase tracking-[.18em] text-muted">01 / Overview</p><p className="text-lg leading-relaxed">{portfolio.profile.about}</p></div></Section>
  <Divider />
  <Section id="experience" title="Experience" count={portfolio.experience.length}><div>{portfolio.experience.map((item) => <article key={item.company} className="grid gap-2 border-b border-line p-5 last:border-0 sm:grid-cols-[150px_1fr] sm:p-6"><p className="font-mono text-xs text-muted">{item.period}</p><div><h3 className="text-lg font-medium">{item.role} <span className="text-muted">at {item.company}</span></h3><p className="mt-2 max-w-xl text-sm leading-relaxed text-muted">{item.description}</p></div></article>)}</div></Section>
  <Divider />
  <Section id="skills" title="Skills"><div className="grid sm:grid-cols-3">{Object.entries(portfolio.skills).map(([category, skills], i) => <div key={category} className="border-b border-line p-5 last:border-0 sm:border-b-0 sm:border-r sm:p-6 sm:last:border-r-0"><p className="mb-4 font-mono text-xs text-muted">0{i + 1} / {category}</p><ul className="space-y-2">{skills.map((skill, skillIndex) => <li key={`${skill}-${skillIndex}`} className="flex items-center gap-2 text-sm"><Check className="size-3 text-accent" />{skill}</li>)}</ul></div>)}</div></Section>
  <Divider />
    <Section id="projects" title="Projects" count={portfolio.projects.length}><div className="grid sm:grid-cols-2">{portfolio.projects.map((project, i) => <article key={project.title} className="group border-b border-line p-5 transition-colors hover:bg-foreground hover:text-background sm:p-6"><div className="mb-12 flex items-center justify-between font-mono text-xs text-muted group-hover:text-background/60"><span>0{i + 1}</span><div className="flex items-center gap-1"><a href={project.website} target="_blank" rel="noreferrer" aria-label={`Open ${project.title} website`} title="Open website" className="flex size-9 items-center justify-center transition-colors hover:bg-background/15 hover:text-background"><Globe2 className="size-4" /></a><a href={project.github} target="_blank" rel="noreferrer" aria-label={`Open ${project.title} GitHub repository`} title="Open GitHub repository" className="flex size-9 items-center justify-center transition-colors hover:bg-background/15 hover:text-background"><Github className="size-4" /></a></div></div><h3 className="text-lg font-medium">{project.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted group-hover:text-background/70">{project.description}</p><div className="mt-5 flex flex-wrap gap-1.5">{project.tags.map((tag) => <span key={tag} className="rounded-full border border-line px-2 py-1 font-mono text-[10px] group-hover:border-background/30">{tag}</span>)}</div></article>)}</div></Section>
  <Divider />
  <Section id="contact" title="Social links"><div className="grid sm:grid-cols-3">{portfolio.socials.map((social) => <a key={social.label} href={social.href} className="flex items-center gap-3 border-b border-line p-5 text-sm transition-colors last:border-0 hover:bg-accent/10 sm:border-b-0 sm:border-r sm:p-6 sm:last:border-r-0"><SocialIcon label={social.label} /><span><strong className="block font-medium">{social.label}</strong><span className="text-xs text-muted">{social.handle}</span></span><MoveRight className="ml-auto size-4 text-muted" /></a>)}</div></Section>
  <footer className="flex flex-col gap-3 border-x border-b border-line px-5 py-6 text-xs text-muted sm:flex-row sm:items-center sm:justify-between"><span>(c) {new Date().getFullYear()} {portfolio.profile.name}</span><a href="#top" className="flex items-center gap-1 font-mono hover:text-foreground">Back to top <span aria-hidden="true">^</span></a></footer>
 </main>
}
